### ISSUE TITLE
0.28在linux下运动不起来

### ISSUE THREAD

**Issue by moboard** [Neutree/PandaTvDanMu#9]
系统是archlinux
ava version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

 java -jar  Neucrack_PandaTV_DanMu/Neucrack_PandaTV_DanMu.jar

发送GET请求出现异常！java.net.ConnectException: 连接超时
java.net.ConnectException: 连接超时

---

用0.27运行起来了

**Comment by Neutree** [comment]
在Ubuntu下面试过，可以用，arch没试过，可以调试下源码看看问题

**Comment by moboard** [comment]
不知道怎么的，又可以 。谢谢啊。
